/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/

function fibEvenSum(number) {
  let x = 1;
  let y = 0;
  let z = 0;
  let sum = 0;

  for (let i = 0; i < number; i++) {
    z = y;
    y = x;
    x = x + z;

    if (x % 2 !== 0) {
      sum += x;
    }
    console.log(`X:${x}, Y:${y}, Z:${z}`);
  }
  console.log(sum);
}

fibEvenSum(15);
